### ISSUE TITLE
Issue 75:	$Override not "asserted to be an override"

### ISSUE THREAD

**Issue by consiliens** [mirah/mirah#124]
"
Reported by rogerdpa...@gmail.com, Jun 1, 2011

``` ruby
class A
  $Override
  def go
  end
end
```

should throw a compile error.
"

http://code.google.com/p/mirah/issues/detail?id=75

**Comment by felixvf** [comment]
Fixed.

**Comment by sara192** [comment]
> "
> Reported by rogerdpa...@gmail.com, Jun 1, 2011
> 
> ``` ruby
> class A
>   $Override
>   def go
>   end
> end
> ```
> 
> should throw a compile error.
> "
> 4910862783e7911eaec8f686716ec9844b65ab5d
>

**Comment by sara192** [comment]
K es este enlace
