### ISSUE TITLE
Add Classes in CLASSPATH Automatically

### ISSUE THREAD

**Issue by fribeiro1** [mirah/mirah#275]
It is counter-intuitive to Java developers needing to pass the current CLASSPATH as in "mirahc -cp $CLASSPATH" or "mirah -cp $CLASSPATH" to compile or run an application with dependencies.

You may want to consider adding classes in the CLASSPATH automatically.

**Comment by baroquebobcat** [comment]
Do you mean that it's weird that if you have `CLASSPATH` defined in your shell, that you'd expect `mirahc` to add it to the compile classpath, and `mirah` to add it to the runtime classpath?

I'll change it to follow java / javac's behavior, so the following happens:

`mirah foo.mirah`, uses default classpath: `.`
`CLASSPATH=<my-cp> mirah foo.mirah`, uses `<my-cp>`
`CLASSPATH=<my-cp> mirah -cp <flag-cp> foo.mirah`, uses `<flag-cp>`

**Comment by fribeiro1** [comment]
Exactly.

**Comment by baroquebobcat** [comment]
Mirah's current default classpath is the destination path, maybe the classpath state machine should be
if cp flag, use flag
if CLASSPATH use CLASSPATH
else use destination

then if you do
```
mirahc -d classes a.mirah
mirahc -d classes b.mirah
```
where `b` depends on `a`, `b` will compile, even though `-cp` wasn't specified. I'll go with that, and see how I feel.

**Comment by fribeiro1** [comment]
I think we should follow the same rules as java/javac, but your proposal also hits the mark.

**Comment by baroquebobcat** [comment]
I think 67d8898b00d6e2fe78305429933ca55193d660f8 should do it.

**Comment by fribeiro1** [comment]
Thanks!
