### ISSUE TITLE
"rake gem" doesn't include mirahc.jar in gem; installed mirah won't execute

### ISSUE THREAD

**Issue by Marand-** [mirah/mirah#278]
I decided to update Mirah today and discovered that the gem created with **rake gem** didn't work.  Attempting to execute **mirah** or **mirahc** results in an error because it can't find class mirah.impl.MirahParser.

I compared the files in the generated *pkg/mirah-0.1.4-java.gem* with the ones installed from the online repo (via **gem install mirah**) and the difference was clear:  the generated gem doesn't contain *dist/mirahc.jar*.  If I manually create *~/.gem/jruby/VER/gems/mirah-0.1.4-java/dist* and copy *mirahc.jar* into it, everything works as expected again.

Tested with a clean mirah dir, freshly cloned from the repo.

**Comment by baroquebobcat** [comment]
Thanks for reporting. I'll try fixing that up.

**Comment by baroquebobcat** [comment]
Hmm. This is peculiar. Running `rake clean gem` locally, the jar is included in the gem I create. Could you tell me a little more about your environment, and post a gist of the output from running `rake gem`?

**Comment by Marand-** [comment]
I've done some more testing, and doing "rake clean gem" on a repo where I've already tried building it before seems to work fine and I get a gemfile with the jar inside as expected.  I get the faulty gem if I follow the directions in README.md to get started from a fresh directory:

```
    $ git clone http://github.com/mirah/mirah.git
    $ cd mirah
    $ bundle install
    $ rake gem
```

After `rake gem` completes, the created gemfile doesn't have the jar in it.  If I `rm -rf pkg` and then `rake gem` a second time, it skips the compile, makes the gem again, but this time adds the jar successfully.  Same happens with `rake clean gem` -- fails to add it the first time on a freshly cloned dir, but after that it works.  I'd been building from the repo for a couple months without issue, but I recently decided to wipe the dir and start over, which is when I ran into this.  

I compared the output of a successful gem creation versus one without the jar, and the difference is that `rake gem` isn't executing the mkdir, rm, or ln for mirahc.jar near the end of the build.  

Providing the lines before/after the mirahc.jar parts for reference, here's how it looks when it adds the jar:
```
ln examples/plugins/appengine/test/com/google/appengine/ext/duby/db/ModelTest.duby pkg/mirah-0.1.4-java/examples/plugins/appengine/test/com/google/appengine/ext/duby/db/ModelTest.duby
mkdir -p pkg/mirah-0.1.4-java/dist
rm -f pkg/mirah-0.1.4-java/dist/mirahc.jar
ln dist/mirahc.jar pkg/mirah-0.1.4-java/dist/mirahc.jar
rm -f pkg/mirah-0.1.4-java/TODO.md
```

and this is what happens when it fails to add mirahc.jar:
```
ln examples/plugins/appengine/test/com/google/appengine/ext/duby/db/ModelTest.duby pkg/mirah-0.1.4-java/examples/plugins/appengine/test/com/google/appengine/ext/duby/db/ModelTest.duby
rm -f pkg/mirah-0.1.4-java/TODO.md
```

I can provide the entire output if needed, but the lack of the mkdir/rm/ln for mirahc.jar seems to be the only change.

I tried looking at the Rakefile to get an idea of why it's doing that, but I know nothing about rake so it was about as useful as you'd expect.  It did give me the idea to try `rake compile` first, followed by `rake gem` separately; that worked fine even on the first go on a freshly cloned repo.

Some system info.  Commands and output:
`jruby --version` : jruby 1.7.17 (2.0.0p195) 2014-12-09 fafd1a7 on OpenJDK Server VM 1.7.0_65-b32 +jit [linux-i386]
`lsb_release -d` :  Description:    Debian GNU/Linux 8.0 (jessie)
(Using 32bit/PAE kernel and 32bit packages)

If I missed anything let me know.

**Comment by baroquebobcat** [comment]
The problem was that the gemspec uses `Dir[]` to look up the jar, and that returns an empty list if the file doesn't exist.

**Comment by Marand-** [comment]
Makes sense.  By the way, thanks for the work on Mirah.  I've never liked Java syntax (and I don't really love Groovy or Scala either), but I find Ruby-style syntax readable and nice to work with, so I greatly appreciate the work done on this project.
