### ISSUE TITLE
support for java 8 interface virtual extension methods

### ISSUE THREAD

**Issue by uujava** [mirah/mirah#279]
I've a workaround for java8 interface default method support. It works if I modify interface_compiler to check for empty method body like this:

src/org/mirah/jvm/compiler/interface_compiler.mirah
```
 def methodFlags(mdef:MethodDefinition, isStatic:boolean)
      if mdef.body.size == 0          
          super | Opcodes.ACC_ABSTRACT
      else
          super
      end
  end
```

It could porbably handled with maco in object extenstion, but I'm not sure what flag to set and how it could be checked in interface compiler or method compiler.

I'd need this change for Ruby module mixin emulation via Java 8 default interface methods. Is it possible to implement it using suggested workaround or in a more proper way?

Thank you for your time,
Vlad

**Comment by baroquebobcat** [comment]
That's a neat idea. I've been wanting to do default method support for a while, but I'd like the implementation to work on earlier Java's somehow. I bet we could work something out.

**Comment by uujava** [comment]
Is it possible to  do quick fix for java8 and add support for earlier Java later?
The retrolambda (https://github.com/orfjackal/retrolambda/issues/31) approach could be taken, but it's a way too complex for me to implement.

**Comment by baroquebobcat** [comment]
Could you put together a quick PR with something that works for you? I'd
like to have a better idea of what that looks like.

Also while you're at it, please post a license grant to the mailing list,
following our contrib guide:
https://github.com/mirah/mirah/wiki/Contributions

**Comment by baroquebobcat** [comment]
This should be fixed. Please reopen if it doesn't work for you.
