### ISSUE TITLE
Multiple class definitions of same name all get compiled separately, overwriting each other

### ISSUE THREAD

**Issue by Marand-** [mirah/mirah#281]
If a mirah source file has multiple class definitions of the same name, they all get compiled separately and overwrite each other, with the final file only having the method definitions of the last class block.  I know Mirah doesn't have Ruby-style open classes, but it still seemed logical that it would combine multiple declarations within the same file into a single class.

For example, in file example.mirah:

```
class Foo
   def bar1
      puts "bar1"
   end
end

class Foo
   def bar2
      puts "bar2"
   end
end

foo = Foo.new
foo.bar2
foo.bar1
```

Invoking `mirahc example.mirah` outputs the following:
```
* [ClassCompiler] Compiling class Example
* [ClassCompiler] Compiling class Foo
* [ClassCompiler] Compiling class Foo
```
If you try to execute the file (either example.mirah or a compiled Example.class), it prints "bar2" and then errors because method bar1 doesn't exist.  The behaviour I expected was to see Mirah compile Foo once, resulting in a Foo class that contained both bar1 and bar2 methods.  Or maybe a compiler error, which would be less useful but still better than silently creating a broken class.

This probably sounds useless, but I found it because I was trying to split a class across multiple files.  I know Java itself can't do that, so `import` won't work, and Mirah doesn't have Ruby's `require`, so I was trying to get similar behaviour by splitting a test class into two files and merging them with `cat split/*.mirah > merged.mirah; mirahc merged.mirah`.

**Comment by Marand-** [comment]
Crap.  Just noticed this was already listed as an open class issue a bit below.  It's late, my bad.  Closing.

**Comment by baroquebobcat** [comment]
no problem. I'll just link it so that the other issue has more context. Open classes issue: #259
