### ISSUE TITLE
LoadError: cannot load such file -- java

### ISSUE THREAD

**Issue by tkeen9** [mirah/mirah#315]
I'm building Mirah from source as described in the documentation:

    $ git clone http://github.com/mirah/mirah.git
    $ cd mirah
    $ bundle install
    $ rake gem
    $ gem install pkg/mirah-*.gem

But when I run `rake gem` I get the following error:

    rake aborted!
    LoadError: cannot load such file -- java
    /home/tkeen9/mirah/Rakefile:24:in `require'
    /home/tkeen9/mirah/Rakefile:24:in `<top (required)>'

When run with the `--trace` parameter there is more info:

    rake aborted!
    LoadError: cannot load such file -- java
    /home/tkeen9/mirah/Rakefile:24:in `require'
    /home/tkeen9/mirah/Rakefile:24:in `<top (required)>'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
    /var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    /usr/local/bin/rake:23:in `load'
    /usr/local/bin/rake:23:in `<main>'

**Comment by tkeen9** [comment]
Solved by installing the latest JRuby version.

**Comment by baroquebobcat** [comment]
Glad you figured it out. Do you think the docs could be updated to make
that less likely?

**Comment by tkeen9** [comment]
@baroquebobcat Yep, I think so. I'm using Debian, but any other distribution based on Debian like Ubuntu install older JRuby versions, namely 1.5. I had to build JRuby 1.7 (the latest as of now) from source.
