### ISSUE TITLE
a==b can be miscompiled to b.equals(b) if method b exists

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#330]
Consider this Mirah code

```mirah

class Foo1
	
	def equals(o:Foo1)
		self===o
	end
end

class Bar
	attr_reader   foo1:Foo1
	attr_reader   foo2:Foo2
	
	def self.main(argv:String[]):void
		Bar.new.foo1method(Foo1.new)
		Bar.new.foo2method(Foo2.new)
	end
	
	def foo1method(foo1:Foo1)
		puts (@foo1==foo1)
		@foo1 = foo1
	end
	
	def foo2method(foo2:Foo2)
		puts (@foo2==foo2)
		@foo2 = foo2
	end
end

class Foo2
	
	def equals(o:Foo2)
		self===o
	end
end
```

It is expected that running "java Bar" yields

```bash
# java Bar
false
false
```

but it can actually be observed that 

```bash
# java Bar
false
true
```

is the result.

## Analysis

Apparently, the compiler cannot resolve the variable "foo2" when compiling foo2method (maybe because the type Foo2 is not yet defined). When encountering the VCall symbol "foo2", it has the choice between deciding that this is a local variable or a method invocation. The compiler erroneously chooses to consider this a method invocation, although a local variable is clearly defined (it is just not resolvable at the time of encountering the method foo2method).

**Comment by baroquebobcat** [comment]
youch. Nice find.
