### ISSUE TITLE
Only false and nil should be considered false

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#383]
Consider this Mirah code

```mirah
if 0
	puts "true"
else
	puts "false"
end
```

According to Ruby semantics, this code should print ```true```.
According to Java semantics, this code should not compile.
It is expected that this could should print ```true``` (as Mirah should feel like Ruby as much as possible).
However, it actually prints ```false```.

**Comment by baroquebobcat** [comment]
Interesting. I would have expected it to be true as well. Are you looking at it?

**Comment by felixvf** [comment]
The culprit seems to be here: https://github.com/mirah/mirah/blob/0af6095bb85e63d4dd190b9eeb7e1c9dca6209e8/src/org/mirah/jvm/compiler/condition_compiler.mirah#L64

The question is: What should happen in case of

```mirah
if somemethod
	puts "true"
else
	puts "false"
end

def somemethod
	puts "somemethod called"
	0
end
```

Should it output just 

```
somemethod called
true
```

or just

```
true
```
?

**Comment by felixvf** [comment]
Maybe we should emit a warning if the result of ```if a``` is that ```a``` is always considered ```true``` due to it being a type being promoted to ```true``` regardless of value, because these statements make no sense if the type of the expression is actually known. They make only sense if the type of the expression is unknown, which may only happen when type inference is so strong that types are not so visible anymore. But maybe we should not emit a warning.

**Comment by felixvf** [comment]
Fixed.

No warnings are emitted.
Code in conditionals is always executed, even if the result is known in advance.
