### ISSUE TITLE
Mirahc fails to access to inherited instance variables

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#391]
Consider this Mirah code:

```mirah
class InheritedInstanceVariableAccessTest < java.io.ByteArrayInputStream
	def count
		@count
	end
end
```

(Note that java.io.ByteArrayInputStream has a protected field "count" of type int.)

Mirahc should compile this code cleanly. But it actually fails with

```
ERROR: InferenceError source:InheritedInstanceVariableAccessTest.mirah start:3 3 end: 3 10 class org.mirah.typer.AssignableTypeFuture
                @@count
                ^^^^^^^
1 errors
```

(Maybe there is a language design reason that this code does not compile. Maybe there should not be an accidental access to an inherited instance variable of an object. But even in this case, there should exist some Mirah language construct to emit bytecode which produces the instance variable access.)

**Comment by uujava** [comment]
I would also vote for proper support for protected and public fields in mirah compiler. 
As far as I could understand, currently, all fields treated private and do not infer like methods by inheritance hierarchy. 
Support for field modifiers already present in FieldCollector, support in Typer is a missing part. 
Do not think that we need additional language construct here if we assume that we could add modifier for a field in a FieldAssign, later validate in FieldCollector there are not conflicting modifiers. 
Note that
```
 def initialize
    protected @x = 1
 end
 
 def some_method 
    volatile @x = 2
 end
```

Could be collected as protected volatile FieldDefinition('x') and emitting compile time warning about adding modifiers in different places. 

Note that static modifier is already emulated by @@x

**Comment by felixvf** [comment]
It turns out that Mirah actually already has support for accessing inherited instance variables:

```mirah
class InheritedInstanceVariableAccessTest < java.io.ByteArrayInputStream
	def initialize
		super(byte[16])
	end
	
	def count2
		count
	end
end
```

compiles successfully and generates proper bytecode to access instance variable ```count``` of class ```java.io.ByteArrayInputStream```.

For each instance variable (including inherited instance variables), a getter and a setter method is synthesized on demand in Mirah space. (This means these methods actually do not exist in bytecode, they are just generated in case there is a method call, and the method call is replaced by an instance variable access.)

So, for practical purposes, this problem does not exist, so I'm closing this issue for now.

However, this interesting behavior should be documented somewhere.

**Comment by uujava** [comment]
For me it looks a bit odd and not. I'd still prefer to have clear indication of field access:

```
class InheritedInstanceVariableAccessTest < java.io.ByteArrayInputStream
    def initialize
        super(byte[16])
    end

    def count2
        @count
    end
end
```
It would be more clear when looking at the code what it's doing. It's also more safe, as if one later define `count` method - code would not change it's behavior.

There is also an issue with setter as 
```
count = 2 
```
and 
```
 self.count = 2
```
has different meaning - first is local variable write, second modifying protected field.

I'd vote for @xxx, @xxx= to infer to inherited fields get or set
and xxx, xxx= never infer to that to avoid issues above.
