### ISSUE TITLE
Constant assignments should have access to local variables

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#399]
Consider this Mirah code

``` mirah
class Foo1
    CONST1 = [1,2,3]
end
```

This code should compile successfully, and it does.

Consider this Mirah code

``` mirah
class Foo2
    CONST2 = [1,2,3].map do |i|
        i+1
    end
end
```

This code should compile successfully, and it does not. The compiler complains:

```
ERROR: can't use local '$gensym1'. (class org.mirah.jvm.mirrors.ClassScope doesn't support locals)
      `result` = java::util::ArrayList.new(`list`.size)
```

Analyzing this further, also this Mirah code

``` mirah
class Foo3
    CONST3 = begin
        a = 5
        b = a+3
        b
    end
end
```

does not compile, but the compiler complains

```
ERROR: can't use local 'a'. (class org.mirah.jvm.mirrors.ClassScope doesn't support locals)
                b = a+3
```

Note that the compiler does not complain about the _assignment_ of local variable "a", just about the _use_ of local variable "a".

It is clear that, at least if the computation is wrapped in a `begin ... end`-block, there should be local variable access, as the code performed is put into a static initializer anyway.

The Ruby interpreter executes the code as expected and without errors.

**Comment by baroquebobcat** [comment]
We probably need a class initializer scope that's similar to a method scope. I think class initializers could just use method scope for now though.
