### ISSUE TITLE
Support nonprivate constants

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#400]
Consider this Mirah code:

```mirah

class Foo
	FOO1 = 1
	FOO2 = 1
end

class Bar
	def bar
		puts Foo.FOO1
	end
end
```

It does not compile, the compiler complains

```
ERROR: Cannot access Foo.FOO1() from Bar
                puts Foo.FOO1
                     ^^^^^^^^
```

because the constant FOO1 is compiled with private access. This is acceptable, as a default. But there needs to be a way to make the constant ```package_protected```, ```protected``` or ```public```. Should the keywords ```package_protected```, ```protected```, ```public```be used for that purpose, as in

```mirah

class Foo
	public FOO1 = 1
	public FOO2 = 1
end
```
? Or should there be other means? One current workaround is

```mirah

class Foo
	FOO1 = 1

	def self.FOO1
		FOO1
	end
	
	FOO2 = 2

	def self.FOO2
		FOO2
	end
end

class Bar
	def bar
		puts Foo.FOO1
	end
end
```

which compiles without errors. But this workaround is ugly, as it contains lots of boilerplate, and may consume more CPU and RAM resources. But maybe that's with intent, as direct constant access circumvents the convention "each access is a method call". Is it intended to make (and keep) constants private at all times to force inter-class-accesses to constants into method calls?

This leads to the next aspect of this issue: In Ruby, constant access uses the double-colon syntax:

```ruby

class Foo
	FOO1 = 1
end

class Bar
	def bar
		puts Foo::FOO1
	end
end
```

In Mirah, constant access currently uses the dot syntax:

```mirah

class Foo
	FOO1 = 1
end

class Bar
	def bar
		puts Foo.FOO1
	end
end
```

To attain consistency, Mirah should also use the double-colon syntax for constant access.

So 3 related aspects:

1. Should direct constant access be discouraged and should each constant access be forced into a method call? If no:
2. We need a syntax to make constants public. Which one is prefered?
3. We should support constant access by the double-colon syntax, shouldn't we?

**Comment by uujava** [comment]
vote for constants to be public by default  and double colon syntax.

**Comment by felixvf** [comment]
Thinking about this issue, it occurs to me that constants are effectively methods which have no parameter and always return the same value. If constants are a special class of methods, then they should inherit the visibility of methods if there is no reason to treat them differently. In Mirah, methods are public by default. Hence, constants should be public by default, too.

This mimics Ruby's behavior, where constants are public by default, too.

Thus, I agree that constants should be public by default, and thus I also vote for that.

**Comment by felixvf** [comment]
The [old Mirah source code](https://github.com/mirah/mirah/blame/2e5ffbd4856d42723079942bd8129f5df21fcf19/src/org/mirah/typer/typer.mirah#L508) also shows that constants are actually intended to be public. Thus, I consider this aspect of this issue settled. Constants being private is actually a bug.

**Comment by baroquebobcat** [comment]
I believe this is fixed on master. I do like bits of #402 though. I could integrate some of it.
