### ISSUE TITLE
Merge mirah-parser into mirah.

### ISSUE THREAD

**Issue by felixvf** [mirah/mirah#403]
It turns out that quite some changes in the mirah project require corresponding changes in the mirah-parser project. Each such change requires a corresponding change of the "javalib/mirah-parser.jar" binary file. Each such change consumes about 300KB in repository history size. Furthermore, 2 parallel changes of the "javalib/mirah-parser.jar" binary file are not easily mergeable.

Thus, the "mirah-parser" project should be merged into the "mirah" project. The "mirah-parser" can still live in a separate directory and be compilable independently, but it should be maintainable and forkable in sync with the "mirah" project.

**Comment by ribrdb** [comment]
I think what we should do is convert the build to use maven instead of keeping the dependencies checked in

**Comment by baroquebobcat** [comment]
I don't particularly want to use maven, but I think moving the parser in makes a lot of sense.

**Comment by felixvf** [comment]
This is fixed in https://github.com/mirah/mirah/tree/0.2.0.
