### ISSUE TITLE
Cannot load Java class mirah.impl.MirahParser?

### ISSUE THREAD

**Issue by scientistnik** [mirah/mirah#419]
Run on java 1.8 `#mirah -e 'puts "Hello, World!"'`! I thought what problem in version jvm, but when I tried use java 1.7.0_95 problem not solved.
 In requirements write that need java 1.7 or higher.

Help please, how to solve this problem?

**Comment by uujava** [comment]
What version of mirah are you using? 
It looks like gem misconfiguration.  I do not use mirah with jruby so could not help with it, but vanilla java is enough to start with mirah. Find mirah jar somewhere (build from sources, download from maven, extract from gem).

Example below assumes java and wget is in your path:
```
wget.exe http://central.maven.org/maven2/org/mirah/mirah/0.1.4/mirah-0.1.4.jar
java -jar mirah-0.1.4.jar --silent -e "puts 'Hello world!'" && java DashE
```
Note, that -e switch just compile DashE class. Check more command line options:
```
java -jar mirah-0.1.4.jar --help 
```

**Comment by scientistnik** [comment]
Yes, *.jar file is work. But for me it is uncomfortably. I want to use mirah in command line. I cloned repo and write path in `$PATH`. Why is not work? Or how else I may use mirah whithout jar-file?
