### ISSUE TITLE
New cast syntax idea

### ISSUE THREAD

**Issue by baroquebobcat** [mirah/mirah#428]
Use the same syntax as declarations, ie `a: Foo` as a general cast syntax. We could then add sugar to assignment as `a: Foo = _`. I think this would be nice because it would disambiguate casting from vcalls etc. It would make hashes more ambiguous though and I haven't thought that through yet.

This would mean that a cast in an ambiguous expression would look like `(a: Foo)`, which I think is more readable than `Foo(a)`. Particularly in chains of casts with calls, eg `((a: Foo).bar: Bar)` as compared with `Bar(Foo(a).bar)`.

Thoughts?

**Comment by felixvf** [comment]
So `foo(c:C)` may mean

1. either "Call method `foo(map:Map)`." with a HashMap which contains one entry.
2. or "Call method `foo(c:C)`." with a parameter which is the value of c?

The optional type annotation on assignments is nice.

Is the space after the colon required?

Does chaining work, such as 

```mirah
b = [3,7,6]:int.map do |i|
  # do something
end
```

?

If we get the hash-ambiguity worked out and chaining works, then this may be a pretty nice syntax.

I'm not very sure whether type annotation "I expect expression X to have type Y" and type conversion "Whatever type expression X has, I want it to be of type Y" should have the same syntax or not. Maybe this should be kept separate, like the distinction between `=` and `==`, maybe not.

**Comment by ribrdb** [comment]
Why replace an ambiguous expression with another? I also think this syntax gets difficult to read as soon as an expression gets more complicated than (a: Foo).

We could make the function call syntax unambiguous if we know the names of all types before inferring method bodies. Is that something worth doing?

Or what about adding a macro to use for all casts? Say 1.as!(float) or float.cast!(1)
(I'm using ! to make sure we don't steal java identifiers).

**Comment by felixvf** [comment]
> Why replace an ambiguous expression with another?

I agree.

> We could make the function call syntax unambiguous if we know the names of all types before inferring method bodies.

IIRC, method bodies are currently allowed to contain class definitions. Some classes are also created by macros, and these in turn are executed by the typer. It could probably be done

> Is that something worth doing?

I guess: no.

> Or what about adding a macro to use for all casts? Say 1.as!(float) or float.cast!(1)

I think that's viable, it depends on how common casts are, whether that syntax is already too long. If it is not too long, then we could live with it.

If it is too long, we could provide a dedicated syntax for them, such as 

```mirah
a!String # cast local variable (or result of method call) 'a' as java.lang.String.
```

or

```mirah
a~String # cast local variable (or result of method call) 'a' as java.lang.String.
```

It seems there are not much more characters available on a US keyboard.

Maybe we could also write

```mirah
a@String # cast local variable (or result of method call) 'a' as java.lang.String.
```

because the '@' sign is currently only used as prefix operator, not as infix operator. The difference is possible, but thin, as 

```mirah
a @String # call method 'a' with 1 parameter, being the value of the instance variable 'String'
```
is valid syntax with a different meaning.

**Comment by uujava** [comment]
I also like postfix notation. What about # sign to use for casts or local variable type hints:
```
a#String = nil
b = 1#Integer
hash = foo(b#Number)#Cloneable.clone#Hashtable
```
Could replace # with any valid postfix sign mentioned above [~!].
I like the #.

**Comment by felixvf** [comment]
Maybe we can put the genie back in the bottle regarding the hash entry syntax:

We define

1. "Identifier COLON WhiteSpace+ Identifier" as hash entry syntax while we define
2. "Identifier WhiteSpace* COLON Identifier" as type annotation syntax

To obtain a hash entry, write at least one whitespace character after the colon.
To obtain a type annotation, write no whitespace after the colon.

So

```mirah
a:String = nil
b = 1:Integer
hash = foo(b:Number):Cloneable.clone:Hashtable
```

would be possible and thus

1. ```foo(c: C)``` means "Call method foo(map:Map)." with a HashMap which contains one entry, while
2. ```foo(c:C)``` means "Call method ```foo(c:C)```." with a parameter which is the value of `c`, type-annotated (and thus casted to) type `C`.

**Comment by uujava** [comment]
Like it. Plan to implement this week.

**Comment by baroquebobcat** [comment]
Awesome! Looking forward to seeing the patch.

**Comment by uujava** [comment]
Stuck a bit with a couple of issues

- The first is an attr_xxx issue. 
attr_xxx macro expects Hash as a parameter, so one have to write additional space when new syntax implemented:
```
attr_accessor x: int, b: String
```
It raises the question "what to do with 'legacy' code"
I tend to reformat mirah compiler code to new syntax requirements. I guess there is not  that plenty of code written in mirah  so it's acceptable from my point.

I particular do not want to rewrite attr_xxx macro to accept NodeList<Cast<SimpleString>,VCall<SimpleString>>

- the second issue is an  old cast notation via function call:
```
str = String(object)
```
I'd like to remove support for this from typer.mirah without any backward compatibility having the same rationale in mind - 'not that plenty of mirah code'.  

I plan to go as described above unless there are better ideas.

**Comment by ribrdb** [comment]
Using spaces in attr_xxx seems inconsistent now.  Can we change attr_xxx to take a variadic list of Casts?

**Comment by uujava** [comment]
It have to accept both a hash and a nodellist of casts accept notations:
```
attr_accessor a:int, b:int # NodeList of Casts
attr_accessor a: int, b: int # Hash
```

If we select only one variant - why shouldn't it the Hash?

**Comment by uujava** [comment]
Created pull request with proposed feature. Please review.

**Comment by felixvf** [comment]
> Using spaces in attr_xxx seems inconsistent now.

I have to agree.

After some weeks, I do not like to require a space after the colon of `attr_accessor` and friends and any other instance of a Hash literal, as in:
```
-  attr_reader context:Context
+  attr_reader context: Context
```

This creates bloat, reduces Ruby syntax compatibility and creates visual ambiguity between casting and Hash syntax. Having an easily accessible Cast syntax is important, but having an easily accessible Hash syntax is more important.

I'm sorry for this being based on an idea I wrote.

Could we use another character for casts, such as `~` TILDE? This character is currently only used as unary prefix operation, not used as a binary infix operation currently, AFAIK, so introduction of a binary infix TILDE operation would be compatible with existing Mirah code and would not create any syntactic incompatibility with exiting Ruby code.

@uujava, I hope you still agree with a `~` TILDE character
> Could replace # with any valid postfix sign mentioned above [~!@].

I still like the postfix notation.

**Comment by uujava** [comment]
Now I think that any sign would we take for cast it will have some issues. Colon was good idea as it's used in method declarations. Having space for hash is lesser evil than introducing new delimiter for type hints. There is not that much compatibility with ruby in mirah anyway.
Technically It's not the problem to use other delimiters, but semantically colon do looks nicer and typed on keyboard faster than other symbol. 
I'd listen to the language designers -

**Comment by ribrdb** [comment]
Personally I like colon since that's what we use in method definitions. But
I think we should be consistent. If there's no space in casts there should
be no space in methods or attr calls.
Or maybe we should just ditch colons for maps and go back to =>
That would remove the ambiguity.

**Comment by felixvf** [comment]
### Survey on casting operators

Here is a small survey on operators for casting to a subtype of a type of an expression in different languages. 

Ruby, Python, JavaScript, R:
	
*	not applicable
      
C, Objective-C, C++, Java, C#:
      
	(NewType) expression

Go:

	NewType(expression)

Delphi:

	expression AS NewType

Rust:

	expression as NewType

Swift:

	expression as! NewType

Scala:
	
	expression.asInstanceOf[NewType]

Groovy:

	(NewType) expression
	expression as NewType
	expression.asType(NewType)

Visual Basic:
	
	CType(expression,NewType)

Matlab:
	
	typecast(expression,NewType)

D:
	
	cast(NewType)expression
	
PL/SQL:
	
	CAST(expression AS NewType)

Mirah suggestion 1:
	
	expression.as(NewType)
	expression~NewType

Mirah suggestion 2 (see below):
	
	expression.as(NewType)
	expression:!NewType

**Comment by felixvf** [comment]
### Availability of a casting macro

Note that regardless of the outcome of the discussion of the casting operator, we can always have a casting macro, such as `Object#as` or `Object#cast`. So the question here is not whether we will have an alternative to the current casting syntax, but given we have an alternative to the current casting syntax, how can we have a shorthand notation in addition to an elaborate notation. Thus, the purpose of the discussion should be the resolution of the question "How can we have a language which allows for concise code?". Hence, the evaluation of the arguments should put weight on whether having one specific shorthand notation makes another specific shorthand notation unavailable, and thus possibly defeats its purpose.  

### Ambiguity with colons

Note that using colons as a casting operator may create another ambiguity:

```mirah
a?foo:bar:baz
```

Is this

```mirah
a ? foo.as(bar) : baz
```

or

```mirah
a ? foo : bar.as(baz)
```

?

### Difference between type annotation and casting

I'd like to point out that there is a difference between type annotation and casting:

1. A type annotation is a hint to the compiler. A type annotation cannot fail at runtime. Currently, no expression can have a type annotation, but method parameters can have a type annotation.
2. A cast is an instruction to the compiler to emit a `checkcast` bytecode instruction, not a mere hint. A cast can fail at runtime. Each expression can have a cast (yielding a new expression), but method parameters cannot have a cast.

So they are superficially similar (in both cases, they have something to do with types), but quite different under the hood.

### Colon Bang

If type annotations are hints while casts are instructions, and the TILDE `~` is not liked, maybe we can have a compromise regarding the syntax of a casting operator: COLON BANG `:!`, as in

```mirah
a:String = nil # variable is annotated
b = 1:!Integer # 1 is casted
hash = foo(b:!Number):!Cloneable.clone:!HashMap
```

The BANG `!` character of COLON BANG `:!` symbolizes

1. that this is an instruction and not merely a hint,
2. that performing the instruction can fail (with a ClassCastException), and
3. that the programmer believes to know better than the compiler.

The COLON `:` character of COLON BANG `:!` symbolizes that it still has to do something with types.

Multi-character operators are not so uncommon, we already have some, such as `==`, `!=`, `<=`, `>=`, `=>`, `**`, `||`, `&&`, `===`, `<<`, `>>`, `::`.

### Summary

So we have currently these options for a casting operator:

1. Casting with the TILDE `~`     operator:

  ```mirah
  attr_accessor foo:Foo
  attr_accessor bar:Bar
  # ...
  def baz(foo:Foo,bar:Bar):String; end
  # ...
  hash = foo(b~Number,c:d,e:f)~Cloneable.clone~HashMap`
  ```

2. Casting with the COLON BANG `:!` operator:

  ```mirah
  attr_accessor foo:Foo
  attr_accessor bar:Bar
  # ...
  def baz(foo:Foo,bar:Bar):String; end
  # ...
  hash = foo(b:!Number,c:d,e:f):!Cloneable.clone:!HashMap`
  ```

3. Casting with the COLON `:`     operator but spaces are required at every `attr_accessor` and every other occurrence of `HashEntry` nodes:


  ```mirah
  attr_accessor foo: Foo
  attr_accessor bar: Bar
  # ...
  def baz(foo: Foo,bar: Bar):String; end
  # ...
  hash = foo(b:Number,c: d,e: f):Cloneable.clone:HashMap`
  ```

I'd prefer 1 over 2, and 2 over 3.

Please state your preferences.

**Comment by uujava** [comment]
Prefer #3, with a bit of comments.
-   spaces are actually not required in method definitions. Parser handle it well:
```
def baz(foo:Foo, bar: Bar): String;end
```
Why should we forbid this flexibility?

- attr_xxx are merely a macro, not the part of the language syntax. They could be `enhanced` to support colon without spaces, but mixed case:
```
attr_accessor x: int, y:String
```
is a bit awkward to implement. 

- code like:
```
foo(b:Number,c: d,e: f)
```
does look confusing.
Good style would be to write:
```
foo(b:Number, {c: d,e: f})
```
but if one like to have option above for some DSL, why not?

- I guess colon hash notation with or without spaces could be implemented in parser for curly braces Hash (require some polishing in parser mmeta):
```
x = {a:B, x:value:String.getLength, c: 123}
```

So the only actual issue is the hash without curly braces

#2 actually clashes with:
```
foo a:!b # Hash with negate operator or cast?
```
#1 clashes with bitwize complement operator, note that it could be overridden:
```
class A
 def ~(foo:Object):int
    "#{@value}_#{foo}"
 end
end
a = A.new
b = "suffix"
puts a~b
```

**Comment by baroquebobcat** [comment]
After playing with it, I'm going with `as!` as a macro, and deprecating / removing the call cast. I might revisit after I get to generics syntax, since that will be touching the syntactical representation of types.

**Comment by felixvf** [comment]
Yay! We have a decision and we can remove call-style casting syntax, fix a host of language ambiguities and thus also increase compiler speed. :-)

It is right to call this not 0.1 anymore but 0.2 due to the syntax change (and thus necessary syntax incompatibility).

If there was a lot of legacy Mirah code, we could make a special Mirah 0.1 compiler which determines which Call node was indeed a Cast node and emits a Mirah 0.2 compatible source code, to aid automatic transition to Mirah 0.2. However, given the current apparent popularity of Mirah, creating a transpiler might not be worthwhile due to the lack of a mount of legacy code (but I may be wrong).

**Comment by baroquebobcat** [comment]
Working on it. :)

as! is nice for a reason I'm just now feeling. It is a whole bunch easier
to search for.

On Aug 6, 2016 3:38 PM, "Felix von Ferey" <notifications@github.com> wrote:

Yay! We have a decision and we can remove call-style casting syntax, fix a
host of language ambiguities and thus also increase compiler speed. :-)

It is right to call this not 0.1 anymore but 0.2 due to the syntax change
(and thus necessary syntax incompatibility).

If there was a lot of legacy Mirah code, we could make a special Mirah 0.1
compiler which determines which Call node was indeed a Cast node and emits
a Mirah 0.2 compatible source code, to aid automatic transition to Mirah
0.2. However, given the current apparent popularity of Mirah, creating a
transpiler might not be worthwhile due to the lack of a mount of legacy
code (but I may be wrong).

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/mirah/mirah/issues/428#issuecomment-238052716>, or mute
the thread

**Comment by baroquebobcat** [comment]
Also, I released 0.2 earlier today. I figured since we've got on the order
of ~500 commits in this release, bumping the minor version is reasonable.

I'm posting the announcement later this evening.

I'm working on some bugs that might lead to a 0.2.1 sooner than later. The
meta circular test didn't cover the parser, and it can't compile with 0.2.
*shrugs*

**Comment by uujava** [comment]
baroquebobcat, 
As I could understand the decision for a.as!(Type) macro over a:Type approach wase mainly due to your vision for generic support  in mirah. Could you please shed some light on this a bit.

Thank you in advance.

**Comment by guai** [comment]
How about a%b templetes syntax? AFAIK it never used yet.

**Comment by guai** [comment]
Lets admit that mirah won't have great tooling any time soon. So it's better reuse those of ruby.
I think mirah should stick with ruby syntax.
Consider following code
```
	attr_reader a % Foo
	attr_reader b % Bar
	def foo(a, b)
		a % Foo; b % Bar

		[1,2].each do |it|
			it % MyClass
			it.my_method
		end

	end % Baz
```
Intellij IDEA does not highlight any line as error and allows to do many useful things such as rename vars, move vars and methods, etc
I believe the same would be in any other ruby IDE
