### ISSUE TITLE
Help regarding extension

### ISSUE THREAD

**Issue by gabru-md** [mirah/mirah#462]
Hello,
I was solving an Issue with Github-Linguistic and I need some information.
What are the extensions associated with the Mirah projects? Is it just `.mirah` because it is what I found in all the repositories. 
I just want to make sure that `.mir` is not a valid Mirah Extension so that I can proceed with the Issue that I have to work on on Linguistics.

Cheers!

**Comment by baroquebobcat** [comment]
Yes. It's just mirah, not mir.

**Comment by gabru-md** [comment]
Thank you so much for the reply.
I shall close this issue then.

:smile:
