### ISSUE TITLE
File I/O example using mirah

### ISSUE THREAD

**Issue by yang-kaist** [mirah/mirah#465]
Dear all.

I'm just trying to learn mirah, and implementing my code with mirah.
But I cannot find any guideline to read/write file using mirah.

I intended to a script which reads the text file and prints their contents.

`import java.io.*`
`BufferedReader.new(FileReader.new("test.txt")).each do |line|`
`    puts line`
`end`

But it  is not compiled with following errors.
`Can't find method java.io.BufferedReader.each(org.mirah.jvm.mirrors.BlockType)`

Isn't there any guide or manual about file I/O using mirah?

Sincerely.

**Comment by uujava** [comment]
Mirah ```each``` is an extention function for a java Iterable. The BufferedReader does not conform to the Iterable interface.
Mirah is merely a Ruby syntax for java and does not provide Ruby IO library itself, so you have to use java IO/NIO API. 

You could read lines from file for example like this:  
```mirah
import java.nio.file.*
Files.lines(Paths.get('test.txt')).forEach { |line|
 puts line 
}
```

As for me - there is not activity in mirah project for a long time. I'd recommend to invest time to learn [Kotlin](https://kotlinlang.org/docs/reference/) instead. Kotlin has some extension helper function for java IO, so "Kotlin" way would be even more consise then "Mirah" one:

```kotlin
import java.io.*;

fun main(vararg args:String) {
	File("test.txt").useLines { println(it) }
}
```

**Comment by yang-kaist** [comment]
Dear uujava,

Thank you for your comment!
With your recommendation,  I'll try to study Kotlin instead.

Sincerely,
Yang
